### ISSUE TITLE
Crashes upon command execution in 1.17.1

### ISSUE THREAD

**Issue by 0x10fox** [MeteorDevelopment/meteor-book-dupe-addon#9]
Using Meteor v0.4.4 build #1136, but i've tested it in the latest build which produced the same result. I tested this in the latest 1.17 build, works fine. Game crashes upon executing .dupe . Here is the log:
[latest.log](https://github.com/MeteorDevelopment/meteor-book-dupe-addon/files/6780635/latest.log)
And here is the crash report:
[crash-2021-07-07_19.57.37-client.txt](https://github.com/MeteorDevelopment/meteor-book-dupe-addon/files/6780641/crash-2021-07-07_19.57.37-client.txt)

**Comment by timoreo22** [comment]
should be fixed if you now use the latest build

**Comment by ef1500** [comment]
I am using the latest dev build (build 1140) and the latest build of the book dupe and it still crashes.
